apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jegj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-jegj@sha256:5b76b0b5a4e6014bea7f6d60b38065140994b08052ea1aa0f189eebe66c0c762
        name: my-nodejs
        resources: {}
status: {}
